<?php
/**
 * RenderingTaskStatus
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\RenderingService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RenderingService API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\RenderingService\Model;
use \Aurigma\RenderingService\ObjectSerializer;

/**
 * RenderingTaskStatus Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\RenderingService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RenderingTaskStatus
{
    /**
     * Possible values of this enum
     */
    const _NEW = 'New';
    const IN_PROGRESS = 'InProgress';
    const COMPLETED = 'Completed';
    const FAILED = 'Failed';
    const REQUEST_FAILED = 'RequestFailed';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::IN_PROGRESS,
            self::COMPLETED,
            self::FAILED,
            self::REQUEST_FAILED,
        ];
    }
}


