<?php
/**
 * RenderingJobsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\RenderingService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RenderingService API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\RenderingService\Test\Api;

use \Aurigma\RenderingService\Configuration;
use \Aurigma\RenderingService\ApiException;
use \Aurigma\RenderingService\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RenderingJobsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\RenderingService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RenderingJobsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for renderingJobsCreate
     *
     * Creates a new rendering job and starts its execution from the very first task..
     *
     */
    public function testRenderingJobsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderingJobsDelete
     *
     * Deletes specified rendering job..
     *
     */
    public function testRenderingJobsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderingJobsDiscard
     *
     * Discards the specified rendering job and prevents its further execution..
     *
     */
    public function testRenderingJobsDiscard()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderingJobsGet
     *
     * Returns a rendering job by ID..
     *
     */
    public function testRenderingJobsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderingJobsGetAll
     *
     * Returns all rendering jobs relevant to the specified query parameters..
     *
     */
    public function testRenderingJobsGetAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderingJobsRecover
     *
     * Recovers the specified rendering job and continues its execution from the failed task..
     *
     */
    public function testRenderingJobsRecover()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderingJobsRestart
     *
     * Restarts the specified rendering job and begins its execution from the very first task..
     *
     */
    public function testRenderingJobsRestart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
